movies/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<int:movie_id>/', movie),
    path('movie_review/add/<int:movie_id>/', add_review),
    path('movie_reviews/<int:movie_id>/', movie_reviews, name='movie_reviews'),
    path('', index)
]

mymovies/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import index

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('movies/', include('movies.urls')),
    path('', index, name='index')
]

users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path('', index, name='index'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
]

movies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=80)
    
    def __str__(self):
        return self.name
    
class Person(models.Model):
    name = models.CharField(max_length=128)
    
    def __str__(self):
        return self.name


class Job(models.Model):
    name = models.CharField(max_length=128)
    
    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(max_length=80)
    overview = models.TextField()
    release_date = models.DateField()
    running_time = models.IntegerField()
    budget = models.IntegerField(blank=True, null=True)
    tmdb_id = models.IntegerField(blank=True, null=True)
    revenue = models.IntegerField(blank=True, null=True)
    poster_path = models.URLField(blank=True, null=True)
    genres = models.ManyToManyField(Genre)
    credits = models.ManyToManyField(Person, through='MovieCredit')
    def __str__(self):
        return f'{self.title} {self.release_date}'

class MovieCredit(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)


class MovieReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1),
                                                          MaxValueValidator(100)])
    review = models.TextField(blank=True)
    title  = models.TextField(blank=False, null=False, default="Reseña sin titulo")

users/models.py
from django.db import models

# Create your models here.

movies/forms.py
from django import forms

class MovieReviewForm(forms.Form):
    rating = forms.IntegerField(label="Calificación", min_value=1, max_value=100, required=True)
    title = forms.CharField(label="Titulo", required=True)
    review = forms.CharField(label="Reseña", min_length=20 ,required=True, 
                             widget =  forms.Textarea(attrs={"class": "block w-full rounded-md bg-white px-3" 
                                  "py-1.5 text-base text-gray-900 outline outline-1"
                                  "-outline-offset-1 outline-gray-300 placeholder:text-gray-400" 
                                  "focus:outline focus:outline-2 focus:-outline-offset-2" 
                                  "focus:outline-indigo-600 sm:text-sm/6"}) ) 
    
    
    title.widget.attrs.update({"class": "block w-full rounded-md bg-white px-3" 
                                  "py-1.5 text-base text-gray-900 outline outline-1"
                                  "-outline-offset-1 outline-gray-300 placeholder:text-gray-400" 
                                  "focus:outline focus:outline-2 focus:-outline-offset-2" 
                                  "focus:outline-indigo-600 sm:text-sm/6"})
    rating.widget.attrs.update({"class": "rounded-md bg-white py-1.5 pl-3 pr-2 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"})

movies/views.py
from django.shortcuts import render
from django.http import HttpResponse
from movies.models import Movie, MovieReview
from movies.forms import MovieReviewForm

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = { 'movies':movies, 'message':'welcome' }
    return render(request,'movies/index.html', context=context )
    
def movie(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    review_form = MovieReviewForm()
    context = { 'movie':movie, 'saludo':'welcome', 'review_form':review_form }
    return render(request,'movies/movie.html', context=context )

def movie_reviews(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request,'movies/reviews.html', context={'movie':movie } )
    
def add_review(request, movie_id):
    form = None
    movie = Movie.objects.get(id=movie_id)
    if request.method == 'POST':
        form = MovieReviewForm(request.POST)
        if form.is_valid():
            rating = form.cleaned_data['rating']
            title  = form.cleaned_data['title']
            review = form.cleaned_data['review']
            movie_review = MovieReview(
                    movie=movie,
                    rating=rating,
                    title=title,
                    review=review,
                    user=request.user)
            movie_review.save()
            return HttpResponse(status=204,
                                headers={'HX-Trigger': 'listChanged'})
    else:
        form = MovieReviewForm()
        return render(request,
                  'movies/movie_review_form.html',
                  {'movie_review_form': form, 'movie':movie})

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    else:
        return render(request,'users/profile.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('index'))
        else:
            # Return an 'invalid login' error message.
            return render(request, 'users/login.html', {'errors':['Invalid Login']})
    else:
        return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

movies/templates/movies/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="{% static 'output.css' %}" rel="stylesheet" />
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}

    {% endblock head %}
    <title> artworks </title>

      <script>
      /*to prevent Firefox FOUC, this must be here*/
        let FF_FOUC_FIX;
      </script>
     <style>

         {% block style %}

         {% endblock style %}
      </style>
  </head>

  <body class="bg-white dark:bg-slate-900" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% block header %}
      {% include "movies/header.html" %} 
    {% endblock header %}


    {% block content %}



    {% endblock content %}

   


    {% block footer%}
<footer class="bg-white">
  <div class="mx-auto max-w-7xl overflow-hidden px-6 py-20 sm:py-24 lg:px-8">
    <nav class="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">
      <div class="pb-6">
        <a href="#" class="text-sm leading-6 text-gray-600 hover:text-gray-900">About</a>
      </div>
      <div class="pb-6">
        <a href="https://github.com/mariosky" class="text-sm leading-6 text-gray-600 hover:text-gray-900">GitHub</a>
      </div>
      <div class="pb-6">
        <a href="https://www.wikiart.org/" class="text-sm leading-6 text-gray-600 hover:text-gray-900"> wikiart.org </a>
      </div>
    </nav>
   
    <p class="mt-10 text-center text-xs leading-5 text-gray-500">&copy; 2021 J. Mario García Valdez</p>
  </div>
</footer>

    {% endblock footer %}

  <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
  <script src="https://unpkg.com/htmx.org@1.8.5" integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script>

  {% block scripts %}

  {% endblock scripts %}

</body>
</html>

movies/templates/movies/header.html
{% load static %}
<nav class="bg-white shadow">
  <div class="mx-auto max-w-7xl px-2 sm:px-4 lg:px-8">
    <div class="flex h-16 justify-between">
      <div class="flex px-2 lg:px-0">
        <div class="flex flex-shrink-0 items-center">
          <img class="h-10 w-auto" src="{% static 'movies/film.png' %}" alt="logo">
        </div>
        <div class="hidden lg:ml-6 lg:flex lg:space-x-8">
          <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
          <a href="/" class="inline-flex items-center border-b-2
                        {% if request.path == '/' %}
                        border-sky-600 
                        {% else %} 
                        border-transparent
                        {% endif %}
                        px-1 
                        pt-1 text-sm font-medium text-blue-900">My Movies</a>
        {% if user.is_authenticated %}
          <a href="/collections" class="inline-flex items-center border-b-2 
                        {% if request.path == '/collections/' %}
                        border-sky-600 
                        {% else %} 
                        border-transparent
                        {% endif %}

                        px-1
                        pt-1 text-sm font-medium text-gray-500 hover:border-gray-300
                        hover:text-gray-700">Mis Peliculas</a>

        {% endif %}
        </div>
      </div>
      <div class="flex flex-1 items-center justify-center px-2 lg:ml-6 lg:justify-end">
        <div class="w-full max-w-lg lg:max-w-xs">
        <form method="get" action="/artworks/search" class="mb-3">
          <label for="search" class="sr-only">Buscar</label>
          <div class="relative">
            <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
              <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clip-rule="evenodd" />
              </svg>
            </div>
            <input id="search" name="search" class="block w-full rounded-md border-0 bg-white py-1.5 pl-10 pr-3 text-gray-900
                            ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2
                            focus:ring-inset focus:ring-indigo-600 
                            sm:text-sm sm:leading-6" placeholder="Buscar" type="search" 
                        {% if search_value != None %} 
                            value="{{ search_value|stringformat:'s' }}"
                        {% endif %} >

          </div>
       </form>
        </div>
      </div>
      <div class="hidden lg:ml-4 lg:flex lg:items-center">


    {% if user.is_authenticated %}
        <div class="relative ml-4 flex-shrink-0">
          <a href="#" class="inline-flex items-center px-1 pt-1 text-sm font-medium text-gray-500"> Hola, {{user.username}} </a>
        </div>
        <div class="relative ml-4 flex-shrink-0">
          <a href="/users/logout" class="inline-flex items-center px-1 pt-1 text-sm font-medium text-sky-700">Termina Sesión</a>
        </div>
    {% else %}
        <div class="relative ml-4 flex-shrink-0">
          <a href="/accounts/register/" class="inline-flex items-center
                        px-1 pt-1 text-sm font-medium text-sky-700"> Regístrate </a>
        </div>
        <div class="relative ml-4 flex-shrink-0">
          <a href="/users/login" class="inline-flex items-center px-1 pt-1 text-sm font-medium text-sky-700">Inicia Sesión</a>
        </div>
    {% endif %}
      </div>
    </div>
  </div>

</nav>

movies/templates/movies/index.html
{% extends "movies/base.html" %}

{% block content %}

<div class="container mx-auto px-5 py-2 lg:px-32 lg:pt-12">
  <div id="artworks-container" class="-m-1 flex flex-wrap md:-m-2">
    {% for movie in movies %}  
    <div class="flex w-1/4 flex-wrap pt-3">
      <div class="w-full p-1 md:p-2">
        <img
          class="block h-full w-full rounded-lg object-cover object-center"
          src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{movie.poster_path}}" alt="{{movie.title}}" />
      </div>
      <div  class=" -m-1 h-10 mt-1 mb-5 "> 
                <a href="/movies/{{movie.id}}" class="block overflow-hidden
                    text-ellipsis pl-5 text-sky-600 font-bold"> {{movie.title|truncatechars_html:40}}  </a>
                <a href="#"  class="block pl-5"> 
                    <span class="text-gray-400 text-sm font-thin"> {{movie.release_date}} </span> </a>
      </div>
    </div>
    {% endfor %} 
  </div>
  <button class="flex w-48 mt-10 justify-center mx-auto rounded-md
        bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white
        shadow-sm hover:bg-indigo-500 focus-visible:outline
        focus-visible:outline-2 focus-visible:outline-offset-2 
        focus-visible:outline-indigo-600"
        hx-get="/movies/random" hx-target="#artworks-container" hx-swap="beforeend"
    >Get More Movies</button>

</div>
{% endblock content %}

movies/templates/movies/movie.html
{% extends "movies/base.html" %}

{% block content %}
<article>
 <div class="container flex mx-auto px-5 py-2 lg:px-32 lg:pt-12 ">
    <div class="overflow-hidden rounded-lg bg-white shadow w-1/3 h-full">
      <div class="px-4 py-5 sm:p-6">
          <div class="w-full p-1 md:p-2">
            <img
              class="block h-full  w-full rounded-lg object-cover object-center"
              src="https://image.tmdb.org/t/p/w600_and_h900_bestv2/{{movie.poster_path}}" alt="{{movie.title}}" />
          </div>
      </div>
      <div class="bg-gray-50 px-4 py-4 sm:px-6">
          <div  class=" -m-1 h-12 mt-1 mb-5 "> 
            <p class="mt-3 pl-8 text-gray-600  font-thin"> Data from: </p>
            <a href="https://www.tmdb.org{{artwork.path}}" class="block overflow-hidden
                        text-ellipsis pl-5 text-sky-600 pb-5"> tmdb.org{{artwork.path}}  </a>
          </div>
      </div>
    </div>
 <div class="overflow-hidden w-1/2 h-full">
    <div class="px-4 py-4 sm:px-6">
          <div  class=" -m-1 mt-1 mb-5 "> 
            <p class="block overflow-hidden
                        text-ellipsis pl-5 dark:text-gray-200 text-xl font-bold"> {{movie.title}} ({{movie.release_date|date:"Y"}}) </p>
                    <p class="mt-1 pl-5 text-gray-600 text-xs font-thin"> 
              {% for g in movie.genres.all %} 
              {{g}} 
              {% if not forloop.last %}
              -
              {% endif %}
              {%endfor%}  </p>
              <div class="flex mt-2">
                <a class="pl-5 text-blue-600 text-sm"   
                 hx-get="/movies/movie_review/add/{{movie.id}}" hx-target="body" hx-swap="beforeend"  href="#">reviews</a> 
                <a class="pl-5 text-red-600 text-sm" href="#">like</a> 
              </div> 
            
            <h1 class="mt-5 text-gray-600 text-base  pl-5 font-semibold">Overview</h1>
            <p class="mt-2 pl-5 text-gray-500 text-sm font-normal font-sans">{{ movie.overview }}</p>
            <p class="mt-5 text-gray-600 text-sm  pl-5 font-semibold"> Credits:
               <p class="mt-2 pl-5 text-gray-600 text-sm  font-thin">
              {% for c in movie.credits.all %} 
              {{c}} {% if not forloop.last %} - {% endif %}
              {%endfor%}  
              </p> 
           <p class="block overflow-hidden mt-6 mb-3
                        text-ellipsis dark:text-gray-200 text-xl font-bold"> Reseñas: </p>
            <div hx-trigger="listChanged from:body" hx-get="{% url 'movie_reviews' movie.id  %}" hx-target="this" >
           
            
            {% include "movies/reviews.html" %}
            
                  
            </div>
 
          
          </div>
        
            
      </div>
    </div>
 </div>
</article>
{% endblock content %}

movies/templates/movies/movie_review_form.html
<div id="modal" _="on closeModal or listChanged remove me" 
    class="relative z-10" role="dialog" aria-modal="true">
  <div class="fixed inset-0 hidden bg-gray-500 bg-opacity-75 transition-opacity md:block"></div>
        <div class="fixed inset-0 z-10 w-screen overflow-y-auto">

<div class="flex w-full mx-auto transform 
            text-left text-base transition 
            md:my-8 md:max-w-2xl md:px-4 lg:max-w-4xl">
         
        <div class="relative flex w-full 
                items-center overflow-hidden bg-white 
                px-4 pb-8 pt-14 shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">
          
        <form hx-post="/movies/movie_review/add/{{movie.id}}/" hx-target="#modal" hx-swap="outerHTML" 
            class="bg-white  w-full  md:col-span-2">
            <div class="px-4 py-3 sm:p-8">
                <p class="block overflow-hidden
                        text-ellipsis mb-4 dark:text-gray-200 text-xl font-bold"> Agrega una Reseña  </p>
             <div class="grid max-w-2xl grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                   <div class="sm:col-span-4">
                            {{movie_review_form}}
                          
                            <div class="text-sm font-medium text-red-600">
                                {{ form.description.errors }}
                            </div>
                </div>
            </div>
         <div class="mt-6 mr-3 flex items-center justify-end gap-x-6">
            <button type="button"  
                    _="on click trigger closeModal" 
                    class="text-sm font-semibold leading-6 text-gray-900">Cancelar</button>
            <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Guardar</button>
          </div>
        </form>


            </div>
        </div>
    </div>
        </div>
</div>

movies/templates/movies/reviews.html
{% for review in movie.moviereview_set.all %} 

<article class="flex max-w-xl flex-col items-start justify-between 	pt-4 pb-6">
          <div class="flex items-center gap-x-4 text-xs">
            <span class="relative z-10 rounded-full 
            {% if review.rating < 60 %}
            bg-red-50 
            {% else %}
            bg-green-50
            {% endif %}
            px-3 py-1.5 
            font-semibold text-base	 text-gray-900 ">{{review.rating}}</span>
          </div>
          <div class="group relative">
            <h3 class="mt-2 text-lg/6 font-semibold text-gray-900 group-hover:text-gray-600">
              <a href="#">
                <span class="absolute inset-0"></span>
                {{review.title}}
              </a>
            </h3>
            
            <p class="mt-1 line-clamp-3 text-sm/6 text-gray-600">
            {{review.review}}
            </p>
          
          </div>
          <div class="relative mt-4 flex items-center gap-x-4">
            <img src="https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" class="size-10 rounded-full bg-gray-50">
            <div class="text-sm/6">
              <p class="font-semibold text-gray-900">
                <a href="#">
                  <span class="absolute inset-0"></span>
                  {{review.user}}
                </a>
              </p>
              <p class="text-gray-600">Usuario desde 2024</p>
            </div>
          </div>
</article> 

{% endfor %} 

users/templates/users/login.html
{% extends "movies/base.html" %}

{% block content %}

<div class="flex min-h-full  justify-center py-10 px-4 sm:px-6 lg:px-8">
    <div  class="border shadow-md rounded-xl px-8 pt-6 pb-8 mb-4 flex flex-col" >
    <div class="mt-6 text-left text-3xl font-bold dark:text-white text-gray-500" > 
    Inicia sesión
  </div>
    {% if errors %}  
        <div class="mt-5 bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4" role="alert">
          <p class="font-bold">Atención:</p>
          <p>Inténtalo de nuevo, el usuario y contraseña no coinciden.</p>
        </div>
     {% endif %}

    <form id='login_form' class="px-8 pt-3 pb-8 mb-4" 
    role="form" method="post" action='{% url "login" %}' xmlns="http://www.w3.org/1999/html">{% csrf_token %}
              	<!-- Username -->
              <div class="block  mt-3 text-gray-700 dark:text-slate-300">
                <input type="text" name="username" placeholder='Usuario'/>
              </div>
              <div class="block mt-3  text-gray-700 dark:text-slate-300">
                <input type="password" name="password" placeholder='Contraseña'/>
              </div>
               <div class="mt-3">
                  <a class="font-medium text-blue-600 dark:text-blue-500 hover:underline"  href="/accounts/password_reset">¿Se te olvidó tu contraseña? </a>
                </div>
              <div class="mt-5 font-medium text-gray-500 dark:text-slate-300"> ¿Aún no te haz registrado? 
                  <a href="/accounts/register" class="mt-3 font-medium text-blue-600 dark:text-blue-500 hover:underline">Regístrate</a></div>

              <div>
                <button type="submit" class="mt-6 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 
                  font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 
                  focus:outline-none dark:focus:ring-blue-800">Inicia Sesión</button>
              </div>
         </form>

</div>
</div>

{% endblock content %}

users/templates/users/profile.html
<h1>Hola {{request.user}}</h1>
<p> <a href='{% url "logout" %}'> Cerrar Sesión</a>  </p>